server:
  port: 8082
  forward-headers-strategy: framework
spring:
  application:
    name: inventory
  datasource:
    username: postgres.uauzcoczgautpaxxomdg
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    password: bwvmOSHwuzGJxbD6
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/api-docs

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s